adminapp/urls.py
from django.urls import include, path
from . import views
from .views import*
app_name='adminapp'
urlpatterns=[
    path('',views.index,name='index'),
    path('articles/', views.articles, name='articles'),
    path('newPost/', views.newPost, name='newPost'),
    path('postes/', views.getPostes, name='postes'),
    path("users/", views.users, name="users"),
    # path('article_list', views.article_list, name='article_list'),
    path('consulate_contacts/', views.consulate_contacts, name='consulate_contacts'),
    path('newConsulate_contact/', views.newConsulate_contact, name='newConsulate_contact'),
    path('delete_consulate_contact/<str:consulate_contact_id>', views.delete_consulate_contact, name='delete_consulate_contact'),
    # path('test/', views.test, name='test')
    path('etat_civils/', views.etat_civils, name='etat_civils'),
    path('newetat_civil/', views.newetat_civil, name='newetat_civil'),
    path('update_etat_civil/<str:etat_civil_id>', views.update_etat_civil, name='update_etat_civil'),
    path('delete_etat_civil/<str:etat_civil_id>', views.delete_etat_civil, name='delete_etat_civil'),
    ##########
    path('visa_infos/', views.visa_infos, name='visa_infos'),
    path('newvisa_info/', views.newvisa_info, name='newvisa_info'),
    path('update_visa_info/<str:visa_info_id>', views.update_visa_info, name='update_visa_info'),
    path('delete_visa_info/<str:visa_info_id>', views.delete_visa_info, name='delete_visa_info'),
]

app1/urls.py
from django.urls import path
from . import views
from .views import*
app_name='stock'
urlpatterns=[
    path('',views.home,name='home'),
    path('consulate/', views.consulate, name='consulate'),
    path('services/', views.services, name='services'),
    path('affaires_sociales/', views.affaires_sociales, name='affaires_sociales'),
    path('services_etrangers/', views.services_etrangers, name='services_etrangers'),
    path('documents_citoyens/', views.documents_citoyens, name='documents_citoyens'),
    path('etat_civil/', views.etat_civil, name='etat_civil'),
    path('announcements/', views.announcements, name='announcements'),
    path('gallery/', views.gallery, name='gallery'),
    path("immatriculation/", views.immatriculation, name="immatriculation"),
    path('studentsInfo/', views.studentsInfo, name='studentsInfo'),
    path('visas/', views.visas, name='visas'),
    path('fonctions_du_consulat/', views.fonctions_du_consulat, name='fonctions_du_consulat'),
    path('contact/', views.contact, name='contact'),
    path('ResidenceauMaroc/', views.ResidenceauMaroc, name="ResidenceauMaroc"),
    
    
    path('details_page/<str:post_id>', view=details_page, name='details_page'),
    path('annoucement_details/<str:annonce_id>', view=annoucement_details, name='annoucement_details'),
    
    path('cv/', view=cv, name='cv'),
    path('bienvenu/', view=bienvenu, name='bienvenu')
    
]

minister_ext/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # path('i18n/', include('django.conf.urls.i18n')),
    # path('admin/', admin.site.urls),
    # path('admin/', include('usersmanagement.urls', namespace='usersmanagement')),
    
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('usersmanagement/', include('usersmanagement.urls', namespace='usersmanagement')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('app1.urls', namespace='app1')),
    # path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    # path('tinymce/', include('tinymce.urls')),
)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)





# urlpatterns = i18n_patterns(
#     path('hello/', your_view),
#     # ... more views here ...
# )

usersmanagement/urls.py
from django.urls import include, path
from . import views
from .views import*
app_name='usersmanagement'
urlpatterns=[
    # path('', include('adminapp.urls', namespace='adminapp')),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('create/', views.create_user, name='create'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('update_password/<str:user_id>', views.update_password, name='update_password'),
    path('update_user/<str:user_id>', views.update_user, name='update_user'),
    path('delete_user/<str:user_id>', views.delete_user, name='delete_user'),
]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from datetime import date
import datetime
from django import forms
# from app1.models import Article

from .models import *
# from django.contrib.auth import Userimport Layout, Field, Div
from django import forms
from django.utils.translation import ugettext_lazy as _
# from tinymce.widgets import TinyMCE

class DateInput(forms.DateInput):
    input_type = 'date'


# class ArticleForm(forms.ModelForm):
#     class Meta:
#         model = Article
#         # fields = ['montant_deposee', 'date_de_depo', 'deposit_type', 'dette', 'client', 'employee', 'description']
        
#         fields = '__all__'
#         article_content = forms.CharField(widget=TinyMCE(attrs={'cols': 80, 'rows': 30}))
#         widgets={
#             'published_date': DateInput()
#         } 


# class ArticleForm(forms.ModelForm):
#     class Meta:
#         model = Article
#         fields = '__all__'
#         widgets = {
#             # 'published_date': DateInput(),
#             # 'content': TinyMCE(attrs={'cols': 46, 'rows': 30}),
#             # 'content': TinyMCE(),
#             'content': forms.Textarea(attrs={'id': 'myTextarea'}),
#         }

adminapp/views.py
from audioop import reverse
from django.shortcuts import redirect, render

# from app1.models import Article
# from adminapp.forms import ArticleForm
from firebase_admin import firestore
from django.utils.safestring import mark_safe
from datetime import datetime

from usersmanagement.decorators import login_required
from django.http import JsonResponse


# def get_content_html(self):
#         return mark_safe(self.content)
# Create your views here.


@login_required
def index(request):
    return render(request, 'adminapp/admin_home.html', {})

@login_required
def articles(request):
    # articles_list = Article.objects.all()
    context = {
        # "articles" : articles_list,
    }
    return render(request,"adminapp/articles.html", context)

# @login_required
def get_postes():
    # Example: Fetch documents from Firestore
    data = []
    docs = firestore.client().collection('postes').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data

@login_required
def get_firestore_data(request):
    # Example: Fetch documents from Firestore
    data = []
    docs = firestore.client().collection('postes').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return render(request, 'home.html', {'data': data})

@login_required
def getPostes(request):
    postes = get_postes()
    print(f"postes : {postes}")
    # articles = Article.objects.all()
    # for article in articles:
    #     print(f'article : {articles}')
    context = {
        'postes': postes,
        # 'articles': articles
    }
    return render(request,'adminapp/postes.html', context)

# @login_required
def addPostes(image_url,video_url,title,author,description,content):
    collection_ref = firestore.client().collection('postes')
    # Get the current date and time
    current_datetime = datetime.now()

    # Format the date and time into a string suitable for an ID
    formatted_datetime = current_datetime.strftime('%Y%m%d%H%M%S')

    # Set the formatted datetime as the document ID
    doc_ref = collection_ref.document(formatted_datetime)
    
    # Data to be added to Firestore
    data = {
        'id':formatted_datetime,
        'image_url': image_url,
        'video_url': video_url,
        'title': title,
        'author': author,
        'description': description,
        'content': mark_safe(content),
        'published_date': formatted_datetime  # You can store the formatted datetime if needed
    }
    # doc_ref = collection_ref.add({
    #             'image': image,
    #             'title': title,
    #             'author':author,
    #             'description': description,
    #             'content': mark_safe(content),
    #             'published_date': 'published_date'
    #         })
    
    # firestore_document_id = doc_ref.id
    
    # Add the data to Firestore
    doc_ref.set(data)
    print(f"doc_ref : {doc_ref}")
    return doc_ref


@login_required
def newPost(request):
    if request.method == 'POST':
        # Get form data
        image_url = request.POST.get('image_url')
        video_url = request.POST.get('video_url')
        title = request.POST.get('title')
        author = request.POST.get('author')
        description = request.POST.get('description')
        content = request.POST.get('content')
        print(f"data : {image_url},{title},{author},{description},{content}")
        # collection_ref = firestore.client().collection('postes')
        # doc_ref = collection_ref.add({
        #             'image': image,
        #             'title': title,
        #             'author':author,
        #             'description': description,
        #             'content': mark_safe(content),
        #             'published_date': 'published_date'
        #         })
        
        doc_ref = addPostes(image_url,video_url,title,author,description,content)
        return redirect('adminapp:newPost')
    else:
        print(f"method is {request.method}")
    
        return render(request,'adminapp/article_Form.html',{})
    
########################################

@login_required
def users(request):
    # Retrieve users from Firestore
    db = firestore.client()
    users_ref = db.collection('users')
    users_data = [user.to_dict() for user in users_ref.stream()]
    print(f"users_data : {users_data}")
    context = {
        'users': users_data,
    }
    return render(request,"adminapp/users.html",context)


################################################

########################################
def get_consulate_contacts():
    data = []
    docs = firestore.client().collection('consulate_contacts').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data

@login_required
def consulate_contacts(request):
    consulate_contacts = get_consulate_contacts()
    print(f"consulate_contacts : {consulate_contacts}")
    context = {
        'consulate_contacts': consulate_contacts,
    }
    return render(request,"adminapp/consulate_contact.html", context)

# @login_required
def addConsulate_contact(address,phoneNumber1,phoneNumber2,email):
    collection_ref = firestore.client().collection('consulate_contacts')
    # Get the current date and time
    current_datetime = datetime.now()

    # Format the date and time into a string suitable for an ID
    formatted_datetime = current_datetime.strftime('%Y%m%d%H%M%S')

    # Set the formatted datetime as the document ID
    doc_ref = collection_ref.document(formatted_datetime)
    
    # Data to be added to Firestore
    data = {
        'id':formatted_datetime,
        'address': address,
        'phoneNumber1': phoneNumber1,
        'phoneNumber2':phoneNumber2,
        'email': email,
    }
    
    # Add the data to Firestore
    doc_ref.set(data)
    print(f"doc_ref : {doc_ref}")
    return doc_ref

@login_required
def newConsulate_contact(request):
    if request.method == 'POST':
        # Get form data
        address = request.POST.get('address')
        phoneNumber1 = request.POST.get('phoneNumber1')
        phoneNumber2 = request.POST.get('phoneNumber2')
        email = request.POST.get('email')
        print(f"data : {address},{phoneNumber1},{phoneNumber2},{email}")
        
        doc_ref = addConsulate_contact(address,phoneNumber1, phoneNumber2,email)
        return redirect('adminapp:newConsulate_contact')
    else:
        print(f"method is {request.method}")
    
        return render(request,'adminapp/consulate_contact_form.html',{})
    
    
@login_required
def delete_consulate_contact(request, consulate_contact_id):
    if request.method == "GET":
        db = firestore.client()
        consulate_contact_ref = db.collection('consulate_contacts').document(str(consulate_contact_id))
        consulate_contact_ref.delete()
    else: 
        print(f"method is {request.method}")
            
    return redirect('adminapp:consulate_contacts')
    
    
#####################################
    
########################################
def get_etat_civils():
    data = []
    docs = firestore.client().collection('etat_civils').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data

@login_required
def etat_civils(request):
    etat_civils = get_etat_civils()
    print(f"etat_civils : {etat_civils}")
    context = {
        'etat_civils': etat_civils,
    }
    return render(request,"adminapp/etat_civils.html", context)

# @login_required
def addetat_civil(type_de_demande,frais):
    collection_ref = firestore.client().collection('etat_civils')
    # Get the current date and time
    current_datetime = datetime.now()

    # Format the date and time into a string suitable for an ID
    formatted_datetime = current_datetime.strftime('%Y%m%d%H%M%S')

    # Set the formatted datetime as the document ID
    doc_ref = collection_ref.document(formatted_datetime)
    
    # Data to be added to Firestore
    data = {
        'id':formatted_datetime,
        "type_de_demande": type_de_demande,
        'frais': frais,
    }
    
    # Add the data to Firestore
    doc_ref.set(data)
    print(f"doc_ref : {doc_ref}")
    return doc_ref

@login_required
def newetat_civil(request):
    if request.method == 'POST':
        # Get form data
        type_de_demande = request.POST.get('type_de_demande')
        frais = request.POST.get('frais')
        print(f"data : {type_de_demande},{frais}")
        
        doc_ref = addetat_civil(type_de_demande ,frais)
        return redirect('adminapp:newetat_civil')
    else:
        print(f"method is {request.method}")
    
        return render(request,'adminapp/etat_civil_form.html',{})
    
    
@login_required
def update_etat_civil(request, etat_civil_id):
    
    if request.method == 'GET':
        # try:
            # Retrieve user data from Firestore
            db = firestore.client()
            etat_civil_ref = db.collection('etat_civils').document(str(etat_civil_id))
            etat_civil_data = etat_civil_ref.get().to_dict()

            if not etat_civil_data:
                return JsonResponse({'success': False, 'message': 'etat_civil not found'})
            
            context = {
                "etat_civil_data" : etat_civil_data
            }
            
            return render(request,"adminapp/update_etat_civil_page.html", context)
            # return JsonResponse({'success': True, 'user': user_data})
        # except Exception as e:
        #     return JsonResponse({'success': False, 'message': str(e)})
        
    if request.method == 'POST':
        # try:
            # Extract user data from POST request
            data = request.POST
            type_de_demande = data.get('type_de_demande')
            frais = data.get('frais')

            # Create or update user in Firestore
            user_data = {
                'id': etat_civil_id,

adminapp/templates/adminapp/admin_home.html
{% extends 'base_admin.html'%}
{% block content %}

{% comment %} <div class="container text-center">
    <div class="row">
      <div class="col">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
      </div>
      <div class="col">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
      </div>
      <div class="col">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
      </div>
      <div class="col">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"> <i class="menu-icon fa fa-glass"></i>Pages</a>
      </div>
    </div>
</div> {% endcomment %}


        <div class="content mt-3">

            <div class="col-sm-12">
                <div class="alert  alert-success alert-dismissible fade show" role="alert">
                    <span class="badge badge-pill badge-success">Bonjour</span> 
                    <p>
                        
                        Bienvenue sur le site Web du Consulat Général de la République Islamique de Mauritanie à Casablanca.

                        En tant qu'administrateur, vous avez accès à une variété de fonctionnalités qui vous permettront de gérer le site Web et de fournir des services aux citoyens mauritaniens résidant au Maroc.
                    </p>
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
            </div>


            <div class="col-sm-6 col-lg-4">
                <div class="card text-white bg-flat-color-1">
                    <div class="card-body pb-0">
                        <a href="{% url 'adminapp:postes' %}" >
                        {% comment %} <h4 class="mb-0">
                            <span class="count">10468</span>
                        </h4> {% endcomment %}
                        <p class="text-light">Visiteurs</p>

                        <div class="chart-wrapper px-0" style="height:70px;" height="70">
                            <canvas id="widgetChart1"></canvas>
                        </div>

                    </div>

                </div>
            </div>
            <!--/.col-->

            <div class="col-sm-6 col-lg-4">
                <div class="card text-white bg-flat-color-2">
                    <div class="card-body pb-0">
                        <a href="{% url 'adminapp:users' %}" >
                        {% comment %} <h4 class="mb-0">
                            <span class="count">10468</span>
                        </h4> {% endcomment %}
                        <p class="text-light">Utilisateurs</p>

                        <div class="chart-wrapper px-0" style="height:70px;" height="70">
                            <canvas id="widgetChart2"></canvas>
                        </div>

                    </div>
                </div>
            </div>
            <!--/.col-->

            {% comment %} <div class="col-sm-6 col-lg-3">
                <div class="card text-white bg-flat-color-3">
                    <div class="card-body pb-0">
                        <a href="{% url 'adminapp:annonces' %}" >
                        <p class="text-light">Annonces</p>

                    </div>

                    <div class="chart-wrapper px-0" style="height:70px;" height="70">
                        <canvas id="widgetChart3"></canvas>
                    </div>
                </div>
            </div> {% endcomment %}
            <!--/.col-->

            <div class="col-sm-6 col-lg-4">
                <div class="card text-white bg-flat-color-4">
                    <div class="card-body pb-0">
                        <a href="{% url 'adminapp:postes' %}" >
                            {% comment %} <h4 class="mb-0">
                                <span class="count">10468</span>
                            </h4> {% endcomment %}
                            <p class="text-light">Nouvelles</p>

                            <div class="chart-wrapper px-3" style="height:70px;" height="70">
                                <canvas id="widgetChart4"></canvas>
                            </div>
                        </a>

                    </div>
                </div>
            </div>
            <!--/.col-->

     


        </div> <!-- .content --> 

{% endblock %}

adminapp/templates/adminapp/articles.html
{% extends 'base_admin.html'%}
{% block content %}
{% endblock%}

adminapp/templates/adminapp/consulate_contact.html
{% extends 'base_admin.html'%}
{% block content %}

<div class="content mt-3">

    <div class="col-sm-12" >
        <div class="col-11 alert  alert-success " role="alert">
            <h3> Gérez vos  <span class="badge badge-pill badge-success">   Contacts du consulat </span> <h3>
        </div>
        <div class="col-1  alert  alert-success">
            <a class="add-btn btn  btn-outline-success" role="button" data-url="#", href="{% url 'adminapp:newConsulate_contact' %}">
                <i class="fa  fa-plus" ></i>
            </a>
        </div>
        <!-- <div class="row">
            <div> Add Address </div>
            <div> Add Numbers </div>
            <div> Add E-mail </div>

        </div> -->
    </div>


    <div class="col-sm-12 col-lg-12">

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Adress</th>
                <th>Numéro de téléphone 1</th>
                <th>Numéro de téléphone 2</th>
                <th>E-mail</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for consulate_contact in consulate_contacts %}
            <tr>
                <td>{{ consulate_contact.address}}</td>
                <td>{{ consulate_contact.phoneNumber1}}</td>
                <td>{{ consulate_contact.phoneNumber2}}</td>
                <td>{{ consulate_contact.email}}</td>
                <th>
                    <a class="delete-btn btn btn-outline-danger" role="button" onclick="return confirm('Etes-vous sûr de vouloir supprimer ce contact du consulat?') ;"  href="{% url 'adminapp:delete_consulate_contact' consulate_contact.id %}">
                        <i class="fa fa-trash-o"></i>
                     </a>  
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock%}

adminapp/templates/adminapp/etat_civils.html
{% extends 'base_admin.html'%}
{% block content %}

<div class="content mt-3">

    <div class="col-sm-12" >
        <div class="col-11 alert  alert-success " role="alert">
            <h3> Gérez vos Informations sur   <span class="badge badge-pill badge-success">  l'Etat Civil</span> <h3>
        </div>
        <div class="col-1  alert  alert-success">
            <a class="add-btn btn  btn-outline-success" role="button" data-url="#", href="{% url 'adminapp:newetat_civil' %}">
                <i class="fa  fa-plus" ></i>
            </a>
        </div>
        <!-- <div class="row">
            <div> Add Address </div>
            <div> Add Numbers </div>
            <div> Add E-mail </div>

        </div> -->
    </div>


    <div class="col-sm-12 col-lg-12">

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Type de demande</th>
                <th>Frais</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            {% for etat_civil in etat_civils %}
            <tr>
                <td>{{ etat_civil.type_de_demande}}</td>
                <td>{{ etat_civil.frais}}</td>
                <th>
                    
                    <a class="update-btn btn btn-outline-success"  role="button" href="{% url 'adminapp:update_etat_civil' etat_civil.id %}" >
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="delete-btn btn btn-outline-danger" role="button" onclick="return confirm('Etes-vous sûr de vouloir supprimer cet état civil ?') ;"  href="{% url 'adminapp:delete_etat_civil' etat_civil.id %}">
                       <i class="fa fa-trash-o"></i>
                    </a> 
            
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock%}

adminapp/templates/adminapp/users.html
{% extends 'base_admin.html'%}
{% block content %}

<div class="content mt-3">

    <div class="col-sm-12" >
        <div class="col-11 alert  alert-success " role="alert">
            <h3> Gérez vos  <span class="badge badge-pill badge-success">   Utilisateurs </span> <h3>
        </div>
        <div class="col-1  alert  alert-success">
            <a class="add-btn btn  btn-outline-success" role="button" data-url="#", href="{% url 'usersmanagement:create' %}">
                <i class="fa  fa-plus" ></i>
            </a>
        </div>
    </div>


    <div class="col-sm-12 col-lg-12">

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th>Prénom</th>
                <th>Nom</th>
                <th>Numéro de téléphone</th>
                <th>E-mail</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>{{ user.firstName}}</td>
                <td>{{ user.lastName}}</td>
                <td>{{ user.phoneNumber }}</td>
                <td>{{ user.email}}</td>
                {% comment %} <th>
                    <a class="delete-btn btn  btn-outline-danger" role="button" data-url="">
                        <i class="fa  fa-edit" ></i>
                    </a>
                    <a class="delete-btn btn  btn-outline-danger" role="button" data-url="#">
                        <i class="fa fa-trash-o" ></i>
                    </a>
                        
                </th> {% endcomment %}

                <th>
                    <a class="update-btn btn btn-outline-success"  role="button" href="{% url 'usersmanagement:update_user' user.id %}" >
                        <i class="fa fa-edit"></i>
                    </a>
                    <a class="delete-btn btn btn-outline-danger" role="button" onclick="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur?') ;"  href="{% url 'usersmanagement:delete_user' user.id %}">
                        <i class="fa fa-trash-o"></i>
                    </a>
                    <a class="clock-btn btn btn-outline-info" role="button" onclick="return confirm('Êtes-vous sûr de vouloir mettre à jour le mot de passe de cet utilisateur?') ;"  href="{% url 'usersmanagement:update_password' user.id %}">
                        {% comment %} <i class="fa fa-clock"></i> {% endcomment %}
                        <i class="fa fa-lock"></i>
                    </a>

                    {% comment %} <a class="delete-btn btn btn-outline-danger" role="button" onclick="confirmDeleteUser('{{ user.id }}')">
                        <i class="fa fa-trash-o"></i>
                    </a> {% endcomment %}
                </th>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% comment %} <script>
    function confirmDeleteUser(userId) {
        var confirmation = confirm('Are you sure you want to delete this user?');

        if (confirmation) {
            // User clicked "OK"
            window.location.href = "{% url 'usersmanagement:delete_user' user.id %}".replace('user.id', userId);
        } else {
            // User clicked "Cancel"
            // You can perform additional actions or simply do nothing
        }
    }
</script> {% endcomment %}
{% endblock%}













{% comment %} {% extends 'base_admin.html'%}
{% block content %}

<div class="content mt-3">

    <div class="col-sm-12">
        <div class="alert  alert-success " role="alert">
            <h3> Manage Your  <span class="badge badge-pill badge-success">   Users </span> <h3> {% endcomment %}
            {% comment %} <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button> {% endcomment %}
        {% comment %} </div>
    </div>


    <div class="col-sm-12 col-lg-12"></div>
</div>
{% endblock%} {% endcomment %}

adminapp/templates/adminapp/visa_infos.html
{% extends 'base_admin.html'%}
{% block content %}

<div class="content mt-3">

    <div class="col-sm-12" >
        <div class="col-11 alert  alert-success " role="alert">
            <h3> Gérez vos Informations sur <span class="badge badge-pill badge-success">  les Visas </span> <h3>
        </div>
        <div class="col-1  alert  alert-success">
            <a class="add-btn btn  btn-outline-success" role="button" data-url="#", href="{% url 'adminapp:newvisa_info' %}">
                <i class="fa  fa-plus" ></i>
            </a>
        </div>
    </div>


    <div class="col-sm-12 col-lg-12">

    <table id="example" class="table table-striped table-bordered" style="width:100%">
        <thead>
            <tr>
                <th> Monde </th>
                <th> Nomber Jours </th>
                <th> Frais </th>
                <th> Actions </th>
            </tr>
            
        </thead>
        <tbody>
            {% for visa_info in visa_infos %}

                <tr>
                    <th rowspan="6" class="mt-6 text-center" > {{ visa_info.monde}} </th>
                    <td>30 jours</td>
                    <td> {{ visa_info.30_jours}}</td>
                    
                    <th rowspan="6" class="mt-6 text-center" > 
                        <a class="update-btn btn btn-outline-success"  role="button" href="{% url 'adminapp:update_visa_info' visa_info.id %}" >
                            <i class="fa fa-edit"></i>
                        </a>
                        <a class="delete-btn btn btn-outline-danger" role="button" onclick="return confirm('Etes-vous sûr de vouloir supprimer ces informations de visa ?') ;"  href="{% url 'adminapp:delete_visa_info' visa_info.id %}">
                           <i class="fa fa-trash-o"></i>
                        </a>     
                    </th>
                </tr>
                <tr>
                    <td>90 jours</td>
                    <td> {{ visa_info.90_jours}} </td>
                    
                </tr>
                <tr>
                    <td>de 3 mois à 1 an</td>
                    <td> {{ visa_info.de_3_mois_à_1_an}} </td>
                    
                </tr>
                <tr>
                    <td>de 1 à 2 ans</td>
                    <td> {{ visa_info.de_1_à_2_ans}} </td>
                   
                </tr>
                <tr>
                    <td>de 2 à 3 ans</td>
                    <td> {{ visa_info.de_2_à_3_ans}} </td>
                    
                </tr>
                <tr>
                    <td>de 3 ans et plus</td>
                    <td> {{ visa_info.de_3_ans_et_plus}} </td>
                    
                </tr>
            
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock%}