app1/urls.py
from django.urls import path
from . import views
from .views import*
app_name='stock'
urlpatterns=[
    path('',views.home,name='home'),
    path('consulate/', views.consulate, name='consulate'),
    path('services/', views.services, name='services'),
    path('affaires_sociales/', views.affaires_sociales, name='affaires_sociales'),
    path('services_etrangers/', views.services_etrangers, name='services_etrangers'),
    path('documents_citoyens/', views.documents_citoyens, name='documents_citoyens'),
    path('etat_civil/', views.etat_civil, name='etat_civil'),
    path('announcements/', views.announcements, name='announcements'),
    path('gallery/', views.gallery, name='gallery'),
    path("immatriculation/", views.immatriculation, name="immatriculation"),
    path('studentsInfo/', views.studentsInfo, name='studentsInfo'),
    path('visas/', views.visas, name='visas'),
    path('fonctions_du_consulat/', views.fonctions_du_consulat, name='fonctions_du_consulat'),
    path('contact/', views.contact, name='contact'),
    path('ResidenceauMaroc/', views.ResidenceauMaroc, name="ResidenceauMaroc"),
    
    
    path('details_page/<str:post_id>', view=details_page, name='details_page'),
    path('annoucement_details/<str:annonce_id>', view=annoucement_details, name='annoucement_details'),
    
    path('cv/', view=cv, name='cv'),
    path('bienvenu/', view=bienvenu, name='bienvenu')
    
]

minister_ext/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # path('i18n/', include('django.conf.urls.i18n')),
    # path('admin/', admin.site.urls),
    # path('admin/', include('usersmanagement.urls', namespace='usersmanagement')),
    
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('usersmanagement/', include('usersmanagement.urls', namespace='usersmanagement')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('app1.urls', namespace='app1')),
    # path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    # path('tinymce/', include('tinymce.urls')),
)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)





# urlpatterns = i18n_patterns(
#     path('hello/', your_view),
#     # ... more views here ...
# )

usersmanagement/urls.py
from django.urls import include, path
from . import views
from .views import*
app_name='usersmanagement'
urlpatterns=[
    # path('', include('adminapp.urls', namespace='adminapp')),
    path('login',views.login,name='login'),
    path('logout',views.logout,name='logout'),
    path('create/', views.create_user, name='create'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('update_password/<str:user_id>', views.update_password, name='update_password'),
    path('update_user/<str:user_id>', views.update_user, name='update_user'),
    path('delete_user/<str:user_id>', views.delete_user, name='delete_user'),
]

usersmanagement/models.py
# from django.db import models

# # Create your models here.

# class User(models.Model):
#     id = models.AutoField(primary_key=True)
#     image = models.ImageField(upload_to='user_images/', null=True, blank=True)
#     firstName = models.CharField(max_length=255)
#     lastName = models.CharField(max_length=255)
#     phoneNumber = models.CharField(max_length=15)
#     email = models.EmailField(unique=True)
#     password = models.CharField(max_length=255)

usersmanagement/views.py
# # Create your views here.

# def login(request):
#     pass

# def register(request):
#     pass

# # views.py

from django.urls import reverse
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.hashers import make_password
from firebase_admin import auth, firestore
from .decorators import login_required
# from .models import User
from datetime import datetime


import hashlib

def md5_hash(text):
    # # Create an MD5 hash object
    # md5_hasher = hashlib.md5()

    # # Update the hash object with the bytes of the input text
    # md5_hasher.update(text.encode('utf-8'))

    # # Get the hexadecimal representation of the hash
    # hashed_text = md5_hasher.hexdigest()

    # return hashed_text
    if text is None:
            raise ValueError("Input text cannot be None")

    # Create an MD5 hash object
    md5_hasher = hashlib.md5()

    # Update the hash object with the bytes of the input text
    md5_hasher.update(text.encode('utf-8'))

    # Get the hexadecimal representation of the hash
    hashed_text = md5_hasher.hexdigest()

    return hashed_text

@login_required
def create_user(request):
    if request.method == 'POST':
        # try:
            # Extract user data from POST request
            data = request.POST
            email = data.get('email')
            password = data.get('password')
            first_name = data.get('firstName')
            last_name = data.get('lastName')
            phone_number = data.get('phoneNumber')
            
            # Get the current date and time
            current_datetime = datetime.now()

            # Format the date and time into a string suitable for an ID
            user_id = current_datetime.strftime('%Y%m%d%H%M%S')

            # # Create user in Firebase Authentication
            # user = auth.create_user(
            #     email=email,
            #     password=password,
            # )

            # Hash the password before saving it to the database
            hashed_password = md5_hash(password)

            # Create or update user in Firestore
            user_data = {
                'id': user_id,
                # 'image': None,  # You can handle image upload separately
                'firstName': first_name,
                'lastName': last_name,
                'phoneNumber': phone_number,
                'email': email,
                'password': hashed_password,
            }

            # Save user data to Firestore
            db = firestore.client()
            user_ref = db.collection('users').document(user_id)
            user_ref.set(user_data)

            return redirect('usersmanagement:create')
        # except Exception as e:
        #     return JsonResponse({'success': False, 'message': str(e)})
        
    context = {}
    return render(request,"usersmanagement/create_user_page.html", context)

    # return JsonResponse({'success': False, 'message': 'Invalid request method'})
    

@login_required
def update_user(request, user_id):
    
    if request.method == 'GET':
        # try:
            # Retrieve user data from Firestore
            db = firestore.client()
            user_ref = db.collection('users').document(str(user_id))
            user_data = user_ref.get().to_dict()

            if not user_data:
                return JsonResponse({'success': False, 'message': 'User not found'})
            
            context = {
                "user_data" : user_data
            }
            
            return render(request,"usersmanagement/update_user_page.html", context)
            # return JsonResponse({'success': True, 'user': user_data})
        # except Exception as e:
        #     return JsonResponse({'success': False, 'message': str(e)})
        
    if request.method == 'POST':
        # try:
            # Extract user data from POST request
            data = request.POST
            email = data.get('email')
            # password = data.get('password')
            first_name = data.get('firstName')
            last_name = data.get('lastName')
            phone_number = data.get('phoneNumber')
            
            # # Get the current date and time
            # current_datetime = datetime.now()

            # # Format the date and time into a string suitable for an ID
            # user_id = current_datetime.strftime('%Y%m%d%H%M%S')

            # # Hash the password before saving it to the database
            # hashed_password = make_password(password)

            # Create or update user in Firestore
            user_data = {
                'id': user_id,
                # 'image': None,  # You can handle image upload separately
                'firstName': first_name,
                'lastName': last_name,
                'phoneNumber': phone_number,
                'email': email,
                # 'password': hashed_password,
            }

            # Save user data to Firestore
            db = firestore.client()
            user_ref = db.collection('users').document(user_id)
            user_ref.set(user_data)

            return redirect('adminapp:users')
        
    # if request.method == 'POST':
    #     return redirect('adminapp:newPost')
    # return JsonResponse({'success': False, 'message': 'Invalid request method'})

def forgot_password(request):
    if request.method == 'POST':
        # try:
            # Extract email from POST request
            email = request.POST.get('email')
            # Retrieve user by email from Firestore
            db = firestore.client()
            users_ref = db.collection('users')
            query = users_ref.where('email', '==', email)
            user_docs = query.stream()
            
            # # Check if any user is found
            # if not user_docs:
            #     return JsonResponse({'success': False, 'message': 'User not found'})

            # # Assuming there's only one user with the given email
            # user_data = user_docs[0].to_dict()
             # Check if any user is found
            user_data = None
            for user_doc in user_docs:
                user_data = user_doc.to_dict()
                print(f"user_data : {user_data}")
                print(f"user_data['id'] : {user_data['id']}")
            
            # Check if any user is found
            if user_docs:
                # redirect('usersmanagement:update_password')
                # Redirect to the update_password page with the user_id parameter
                return redirect(reverse('usersmanagement:update_password', kwargs={'user_id': user_data['id']}))
            # redirect("usersmanagement:update_password" user_data['id'])

        #     # Send password reset email
        #     auth.generate_password_reset_link(email)

        #     return JsonResponse({'success': True, 'message': 'Password reset email sent'})
        # except Exception as e:
        #     return JsonResponse({'success': False, 'message': str(e)})

    return render(request,"usersmanagement/forget_password.html", {})


def update_password(request, user_id):
    if request.method == 'POST':
        # try:
            # Extract new password from POST request
            new_password = request.POST.get('password')

            # Hash the new password before saving it
            hashed_password = md5_hash(new_password)

            # # Update password in Firebase Authentication
            # user = auth.get_user(str(user_id))
            # auth.update_user(
            #     user.uid,
            #     password=new_password,
            # )

            # Update hashed password in Firestore
            db = firestore.client()
            user_ref = db.collection('users').document(str(user_id))
            user_ref.update({'password': hashed_password})
            
            # redirect('usersmanagement:login')

            return JsonResponse({'success': True, 'message': 'Password updated successfully'})
        # except Exception as e:
        #     return JsonResponse({'success': False, 'message': str(e)})

    return render(request,"usersmanagement/update_password_page.html", {"user_id":user_id})

@login_required
def delete_user(request, user_id):
    if request.method == "GET":
        db = firestore.client()
        user_ref = db.collection('users').document(str(user_id))
        user_ref.delete()
    else: 
        print(f"method is {request.method}")
            
    return redirect('adminapp:users')


# def get_user_by_email_password(email, password):
#    # Save user data to Firestore
#     db = firestore.client()
#     user_ref = db.collection('users')
#     # Hash the password before saving it to the database
#     hashed_password = make_password(password)
#     query = user_ref.where('email', '==', str(email)).where('password', '==', hashed_password)

#     user_docs = query.stream()
#     # user_data = user_docs[0].to_dict()
    
#     # for user_doc in user_docs:
#     #     user_data = user_doc.to_dict()
#     #     return user_data
#     # return user_data
    
#     user_data = None
#     for user_doc in user_docs:
#         user_data = user_doc.to_dict()
#         print(f"user_data : {user_data}")
#         print(f"user_data['id'] : {user_data['id']}")
        
#     if user_docs:
#         return user_docs

# import bcrypt

# def hash_password(password):
#     # Generate a salt and hash the password
#     salt = bcrypt.gensalt()
#     hashed_password = bcrypt.hashpw(password.encode('utf-8'), salt)
    
#     # Convert the hashed password to a string for storage
#     return hashed_password.decode('utf-8')

# def check_password(password, hashed_password):
#     # Check if the provided password matches the hashed password
#     return bcrypt.checkpw(password.encode('utf-8'), hashed_password.encode('utf-8'))


# @login_required
def get_user_by_email_password(email, password):
    db = firestore.client()
        

usersmanagement/templates/usersmanagement/create_user_page.html
{% extends 'base_admin.html'%}
{% load static %}

{% block content %}


<div class="container">
    <div class="col-sm-12">
        <div class="alert  alert-success " role="alert">
            <h3> Créer un nouveau  <span class="badge badge-pill badge-success">   Utilisateur </span> <h3>
        </div>
    </div>        
    <div class="modal-body ">
        <!-- form -->
        <form method="POST" action=" {% url 'usersmanagement:create' %} ">
          {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="firstName">Prénom</label>
                <input type="text" class="form-control" id="firstName" name="firstName" class="form-control"  placeholder="First Name">
              </div>
              <div class="form-group col-md-6">
                <label for="lastName">Nom:</label>
                <input type="text" class="form-control" id="lastName" name="lastName"  class="form-control" placeholder="Last Name">
              </div>
            </div>
            <div class="form-group">
                <label for="phoneNumber">Numéro de téléphone:</label>
                <input type="number" class="form-control" id="phoneNumber" name="phoneNumber" class="form-control"  placeholder="Phone Number">
            </div>
            <div class="form-group">
                <label for="email">E-mail:</label>
                <input type="email" class="form-control" id="email" name="email" class="form-control"  placeholder="Email">
            </div>
            <div class="form-group">
                <label for="password">Mot de passe:</label>
                <input name="password" required="required" type="password" class="form-control" id="userPassword">
            </div> 
            {% comment %} <div class="form-group">
                <label for="password">Password:</label>
                <input name="password" required="required" type="password" class="form-control" id="userPassword">
            </div> {% endcomment %}
           
           
            {% comment %} <button type="submit" class="btn btn-primary"> Publier </button> {% endcomment %}
            <div>
                <button id="payment-button" type="submit" class="btn btn-lg btn-success btn-block ">
                    {% comment %} <i class="fa fa-sending fa-sending"></i>&nbsp; {% endcomment %}
                    <span id="payment-button-amount">Registre</span>
                    {% comment %} <span id="payment-button-sending" style="display:none;">en cours de Publication ………</span> {% endcomment %}
                </button>
            </div>
          </form>
    </div>
</div>

{% endblock%}

usersmanagement/templates/usersmanagement/forget_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Login Page</title>
    <style>
        #login img {
            margin: 100px 0 30px 0;
        }

        #login .center {
            text-align: center;
        }

        #login .login {
            max-width: 600px;
            margin: 35px auto;
        }

        #login .login-form {
            padding: 0px 25px;
        }
    </style>
</head>
<body>
    <div id="login" class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="login well well-sm">
                    <div class="center">
                        <img src="{% static 'logo.ico' %}" alt="Forget Password">
                    </div>
                    <div class="modal-body ">
                        <!-- form -->
                        <form method="POST" action=" {% url 'usersmanagement:forgot_password' %} ">
                          {% csrf_token %}
                            
                            <div class="form-group">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" id="email" name="email" class="form-control"  placeholder="Email">
                            </div>
                            <div>
                                <button id="payment-button" type="submit" class="btn btn-lg btn-success btn-block ">
                                    {% comment %} <i class="fa fa-sending fa-sending"></i>&nbsp; {% endcomment %}
                                    <span id="payment-button-amount">Register</span>
                                    {% comment %} <span id="payment-button-sending" style="display:none;">en cours de Publication ………</span> {% endcomment %}
                                </button>
                            </div>
                          </form>
                    </div>
                </div><!--/.login-->
            </div><!--/.col-md-12-->
        </div><!--/.row-->
    </div><!--/.container-->

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

usersmanagement/templates/usersmanagement/login_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Login Page</title>
    <style>
        #login img {
            margin: 100px 0 30px 0;
        }

        #login .center {
            text-align: center;
        }

        #login .login {
            max-width: 600px;
            margin: 35px auto;
        }

        #login .login-form {
            padding: 0px 25px;
        }

        .error-message {
            color: #ff0000;
        }
    </style>
</head>
<body>
    <div id="login" class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="login well well-sm">
                    <div class="center">
                        <img src="{% static 'logo.ico' %}" alt="Login">
                    </div>
                    <div class="modal-body">
                        <!-- form -->
                        <form method="POST" action="{% url 'usersmanagement:login' %}" >
                            {% csrf_token %}

                            <div class="form-group">
                                <label for="email">Email:</label>
                                <input type="email" class="form-control" id="email" name="email" class="form-control"  placeholder="Email">
                            </div>
                            
                            <div class="form-group">
                                <label for="password"> Password:</label>
                                <input name="password" required="required" type="password" class="form-control" id="userPassword">
                            </div> 
                            <div>
                                <button id="payment-button" type="submit" class="btn btn-lg btn-success btn-block ">
                                    <span id="payment-button-amount">Login</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div><!--/.login-->
            </div><!--/.col-md-12-->
        </div><!--/.row-->
    </div><!--/.container-->

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>

usersmanagement/templates/usersmanagement/update_password_page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <title>Login Page</title>
    <style>
        #login img {
            margin: 100px 0 30px 0;
        }

        #login .center {
            text-align: center;
        }

        #login .login {
            max-width: 600px;
            margin: 35px auto;
        }

        #login .login-form {
            padding: 0px 25px;
        }

        .error-message {
            color: #ff0000;
        }
    </style>
</head>
<body>
    <div id="login" class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="login well well-sm">
                    <div class="center">
                        <img src="{% static 'logo.ico' %}" alt="Reset Password">
                    </div>
                    <div class="modal-body">
                        <!-- form -->
                        <form method="POST" action="{% url 'usersmanagement:update_password' user_id %}" onsubmit="return validatePassword()">
                            {% csrf_token %}
                            
                            <div class="form-group">
                                <label for="password">Nouveau mot de passe:</label>
                                <input name="password" required="required" type="password" class="form-control" id="userPassword">
                            </div> 
                            <div class="form-group">
                                <label for="confirm_password">Confirmez le mot de passe:</label>
                                <input name="confirm_password" required="required" type="password" class="form-control" id="confirmPassword">
                                <p id="passwordMatchError" class="error-message"></p>
                            </div> 
                            <div>
                                <button id="payment-button" type="submit" class="btn btn-lg btn-success btn-block ">
                                    <span id="payment-button-amount">mettre à jour le mot de passe</span>
                                </button>
                            </div>
                        </form>
                    </div>
                </div><!--/.login-->
            </div><!--/.col-md-12-->
        </div><!--/.row-->
    </div><!--/.container-->

    <!-- Bootstrap JS and dependencies -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <script>
        function validatePassword() {
            var newPassword = document.getElementById("userPassword").value;
            var confirmPassword = document.getElementById("confirmPassword").value;
            var errorElement = document.getElementById("passwordMatchError");

            if (newPassword !== confirmPassword) {
                errorElement.textContent = "Passwords do not match!";
                return false;
            } else {
                errorElement.textContent = ""; // Clear any previous error messages
                return true;
            }
        }
    </script>
</body>
</html>

usersmanagement/templates/usersmanagement/update_user_page.html
{% extends 'base_admin.html'%}
{% load static %}

{% block content %}


<div class="container">
    <div class="col-sm-12">
        <div class="alert  alert-success " role="alert">
            <h3> Mettre à jour <span class="badge badge-pill badge-success"> l'utilisateur </span> <h3>
        </div>
    </div>        
    <div class="modal-body ">
        <!-- form -->
        <form method="POST" action=" {% url 'usersmanagement:update_user' user_data.id %} ">
          {% csrf_token %}
            <div class="form-row">
              <div class="form-group col-md-6">
                <label for="firstName">Prénom:</label>
                <input type="text" class="form-control" id="firstName" name="firstName" class="form-control"  placeholder="First Name" value={{user_data.firstName}}>
              </div>
              <div class="form-group col-md-6">
                <label for="lastName">Nom:</label>
                <input type="text" class="form-control" id="lastName" name="lastName"  class="form-control" placeholder="Last Name" value={{user_data.lastName}}>
              </div>
            </div>
            <div class="form-group">
                <label for="phoneNumber">Numéro de téléphone:</label>
                <input type="number" class="form-control" id="phoneNumber" name="phoneNumber" class="form-control"  placeholder="Phone Number" value={{user_data.phoneNumber}}>
            </div>
            <div class="form-group">
                <label for="email">E-mail:</label>
                <input type="email" class="form-control" id="email" name="email" class="form-control"  placeholder="Email" value={{user_data.email}}>
            </div>
            {% comment %} <div class="form-group">
                <label for="password">Password:</label>
                <input name="password" required="required" type="password" class="form-control" id="userPassword">
            </div>  {% endcomment %}
            {% comment %} <div class="form-group">
                <label for="password">Password:</label>
                <input name="password" required="required" type="password" class="form-control" id="userPassword">
            </div> {% endcomment %}
           
           
            {% comment %} <button type="submit" class="btn btn-primary"> Publier </button> {% endcomment %}
            <div>
                <button id="payment-button" type="submit" class="btn btn-lg btn-success btn-block ">
                    {% comment %} <i class="fa fa-sending fa-sending"></i>&nbsp; {% endcomment %}
                    <span id="payment-button-amount">Mettre à jour</span>
                    {% comment %} <span id="payment-button-sending" style="display:none;">en cours de Publication ………</span> {% endcomment %}
                </button>
            </div>
          </form>
    </div>
</div>

{% endblock%}