app1/urls.py
from django.urls import path
from . import views
from .views import*
app_name='stock'
urlpatterns=[
    path('',views.home,name='home'),
    path('consulate/', views.consulate, name='consulate'),
    path('services/', views.services, name='services'),
    path('affaires_sociales/', views.affaires_sociales, name='affaires_sociales'),
    path('services_etrangers/', views.services_etrangers, name='services_etrangers'),
    path('documents_citoyens/', views.documents_citoyens, name='documents_citoyens'),
    path('etat_civil/', views.etat_civil, name='etat_civil'),
    path('announcements/', views.announcements, name='announcements'),
    path('gallery/', views.gallery, name='gallery'),
    path("immatriculation/", views.immatriculation, name="immatriculation"),
    path('studentsInfo/', views.studentsInfo, name='studentsInfo'),
    path('visas/', views.visas, name='visas'),
    path('fonctions_du_consulat/', views.fonctions_du_consulat, name='fonctions_du_consulat'),
    path('contact/', views.contact, name='contact'),
    path('ResidenceauMaroc/', views.ResidenceauMaroc, name="ResidenceauMaroc"),
    
    
    path('details_page/<str:post_id>', view=details_page, name='details_page'),
    path('annoucement_details/<str:annonce_id>', view=annoucement_details, name='annoucement_details'),
    
    path('cv/', view=cv, name='cv'),
    path('bienvenu/', view=bienvenu, name='bienvenu')
    
]

minister_ext/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    # path('i18n/', include('django.conf.urls.i18n')),
    # path('admin/', admin.site.urls),
    # path('admin/', include('usersmanagement.urls', namespace='usersmanagement')),
    
    path('admin/', include('adminapp.urls', namespace='adminapp')),
    path('usersmanagement/', include('usersmanagement.urls', namespace='usersmanagement')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns(
    path('', include('app1.urls', namespace='app1')),
    # path('adminapp/', include('adminapp.urls', namespace='adminapp')),
    # path('tinymce/', include('tinymce.urls')),
)
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)





# urlpatterns = i18n_patterns(
#     path('hello/', your_view),
#     # ... more views here ...
# )

app1/models.py
# from django.db import models
# # from tinymce.models import HTMLField
# from django.utils.translation import gettext_lazy as _
# from django.utils.safestring import mark_safe

# class Article(models.Model):
#     # image = models.FileField(_("Image"), upload_to='uploads/', default=None)
#     title = models.CharField(_("Title"),max_length=200)
#     author = models.CharField(_("Author"),max_length=100)
#     content = models.TextField()
#     # content = HTMLField(_("Content"),)
#     published_date = models.DateTimeField(_("Published date"),auto_now_add=True)
    
#     def get_content_html(self):
#         return mark_safe(self.content)
    
    
#     class Meta:
#         verbose_name = _("Article")
#         verbose_name_plural = _("Articles")

#     def __str__(self):
#         return self.title
    
    
# class Test(models.Model):
#     name = models.CharField(max_length=255)
#     description = models.TextField()
#     firestore_document_id = models.CharField(max_length=255, blank=True, null=True)

#     def to_dict(self):
#         return {
#             'name': self.name,
#             'description': self.description,
#             'firestore_document_id': self.firestore_document_id
#         }
 

app1/views.py
from django.shortcuts import render
# from .models import Article

# views.py

from django.shortcuts import render
from firebase_admin import firestore

consulate_contacts = {}
# Create your views here.
def get_consulate_contacts():
    consulate_contacts = {}
    docs = firestore.client().collection('consulate_contacts').stream()
    for doc in docs:
        consulate_contacts = doc.to_dict()
        
    print(f"consulate_contacts : {consulate_contacts}")
    return consulate_contacts



def cv(request):
    return render(request, 'app1/cv.html', {'consulate_contacts':consulate_contacts})

def bienvenu(request):
    return render(request, 'app1/bienvenue.html', {'consulate_contacts':consulate_contacts})

def home(request):
    global consulate_contacts
    # articles = Article.objects.all().order_by('-published_date')
    # context = {'articles': articles}
    postes = get_postes()
    annonces = get_annoncements()
    consulate_contacts = get_consulate_contacts()
    
    # postes = []
    # annonces = []
    
    context = {
        'postes': postes,
        'annonces': annonces,
        'consulate_contacts':consulate_contacts
    }
    
    return render(request, 'app1/home.html', context)


def get_object_by_id(collection_name, document_id):
    """
    Retrieve a Firestore document based on the document ID.

    Args:
        collection_name (str): The name of the Firestore collection.
        document_id (str): The ID of the document to retrieve.

    Returns:
        dict or None: The document data if found, or None if not found.
    """
    # Initialize Firestore client and reference to the collection
    db = firestore.client()
    collection_ref = db.collection(collection_name)

    # Get the document reference based on the document_id
    doc_ref = collection_ref.document(document_id)

    # Retrieve the document snapshot
    doc_snapshot = doc_ref.get()

    # Check if the document exists
    if doc_snapshot.exists:
        # Return the document data
        return doc_snapshot.to_dict()
    else:
        # Document not found
        return None


def details_page(request, post_id):
    poste = get_object_by_id("postes", post_id)
    # print(f"poste.video_url : {poste.video_url}")
    if(poste['video_url'] == ""):
        print(f"poste : {poste['video_url']}")
    
    context = {
        "poste": poste,
        'consulate_contacts':consulate_contacts
    }
    return render(request, 'app1/details_page.html', context)

def annoucement_details(request, annonce_id):
    annonce = get_object_by_id("annonces", annonce_id)
    # print(f"poste.video_url : {poste.video_url}")
    if(annonce['video_url'] == ""):
        print(f"annonce : {annonce['video_url']}")
    
    context = {
        "annonce": annonce,
        'consulate_contacts':consulate_contacts
    }
    return render(request, 'app1/annoucement_details.html', context)

def consulate(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, 'app1/consulate.html', context)

def services(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, 'app1/services.html', context)

def affaires_sociales(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, 'app1/affaires_sociales.html', context)

def services_etrangers(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, 'app1/services_etrangers.html', context)

def documents_citoyens(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, 'app1/documents_citoyens.html', context)


def get_etat_civils():
    data = []
    docs = firestore.client().collection('etat_civils').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data


def etat_civil(request):
    etat_civils = get_etat_civils()
    
    context = {
        'consulate_contacts':consulate_contacts,
        'etat_civils' : etat_civils
    }
    return render(request, 'app1/etat_civil.html', context)


def get_postes():
    # Example: Fetch documents from Firestore
    data = []
    docs = firestore.client().collection('postes').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data

def get_annoncements():
    data = []
    docs = firestore.client().collection('annonces').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data



def announcements(request):
    postes = get_postes()
    annonces = get_annoncements()
    
    context = {
        'postes': postes,
        'annonces': annonces,
        'consulate_contacts':consulate_contacts
    }
    return render(request, 'app1/announcements.html', context)

def gallery(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, 'app1/gallery.html', context)
def immatriculation(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request,"app1/immatriculation.html", context)

def studentsInfo(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request,"app1/studentsinfo.html", context)


def get_visa_infos():
    data = []
    docs = firestore.client().collection('visa_infos').stream()
    for doc in docs:
        data.append(doc.to_dict())
        
    print(f"data : {data}")
    return data


def visas(request):
    visa_infos = get_visa_infos()
    context = {
        'consulate_contacts':consulate_contacts,
        'visa_infos': visa_infos,
    }
    return render(request,"app1/visas.html",context)

def fonctions_du_consulat(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request,"app1/fonctions_du_consulat.html", context)

def contact(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request,"app1/contact.html", context)

def ResidenceauMaroc(request):
    context = {'consulate_contacts':consulate_contacts}
    return render(request, "app1/ResidenceauMaroc.html",context)

app1/templates/app1/ResidenceauMaroc.html
{% extends 'base.html' %}
{% load i18n %}

{%get_current_language as LANGUAGE_CODE%}


{% block content %}


<div class="col">
    <br>
    <br>
    <div class="col text-justify">
       
        <h2 class="text-center">{% trans "الإقامة بالمغرب"%}</h2>
        <br>
        <p class="{%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left ">
            {% trans "يتم تقديم طلبات الإقامة لدى مصالح الشرطة المختصة ويتكون الملف عادة من:" %}
        </p>
        <ul class="{%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left">
            <li>{% trans "جواز السفر وتأشيرة الدخول (بالنسبة للطلاب يجب ان يحصلوا على تأشيرة طالب من السفارة أو القنصلية المغربية مسبقا)" %}</li>
            <li>{% trans "عقد إيجار(يحدد عنوان السكن) أو إفادة ملكية في حالة الملكية، أو إفادة سكن في حي جامعي بالنسبة للطلاب" %}</li>
            <li>{% trans "إفادة منحة بالنسبة للطلاب الممنوحين" %}</li>
            <li>{% trans "إفادة تكفل بالنسبة للطلاب غير الممنوحين" %}</li>
            <li>{% trans "تسجيل قنصلي" %}</li>
        </ul>
    </div>
</div>

{% endblock %}

app1/templates/app1/affaires_sociales.html
{% extends 'base.html' %}
{% load i18n %}

{%get_current_language as LANGUAGE_CODE%}


{% block content %}


<div class="col">
    <br>
    <br>

    <div class="col text-justify">
        <h2 class="text-center">{% trans "الشؤون الاجتماعية" %}</h2>
        <br>
        <p class="text-justify">
            {% trans "تتولى المصلحة المكلفة بالعمل الاجتماعي في القنصلية متابعة وتنسيق ملف التعاون في مجال التكفل الطبي للمواطنين الموريتانيين الذين يتابعون العلاج في المستشفيات المغربية، والذين تتكلف الدولة بعلاجهم(من خلال وزارة العمل الاجتماعي)،" %}
            {% trans "تتمثل المهمة العامة للمصلحة في برمجة وتنسيق المواعيد الطبية لهؤلاء وتوجيههم للمستشفيات، وكذلك توفير وثائق التكفل اللازمة." %}
        </p>
    </div>
</div>

{% endblock %}

app1/templates/app1/annoucement_details.html
{% extends 'base.html'%}
{%load static %}
{% comment %} {% load i18n %}

{%get_current_language as LANGUAGE_CODE%} {% endcomment %}


{% block content %}


<div class="card col-lg-12 text-justify" >
{% comment %} text-right" > {% endcomment %}
    {% if annonce.video_url == "" %}
        <img class="card-img-top" src="{{ annonce.image_url }}" height="500" alt="Card image cap">
    {% else %}
        <div class="card-img-top">
            <div class="embed-responsive embed-responsive-16by9">
                <!-- Replace the YouTube video URL in the src attribute -->
                <iframe class="embed-responsive-item" src="{{ annonce.video_url }}" allowfullscreen></iframe>
            </div>
        </div>
    {% endif %}
    <div class="card-body">
      <h4 class="card-title text-center ">{{annonce.title}}</h4>
      <p class="card-text">{{ annonce.content | safe }}</p>
      <div class='col'>
        {% comment %} <span>{{poste.author}}</span> {% endcomment %}
        <span>{{annonce.published_date}}</span>
      </div>
    </div>
</div>





{% endblock %}

app1/templates/app1/bienvenue.html
{% extends 'base.html'%}
{%load static %}
{% load i18n %}
{% comment %} {% load i18n %}

{%get_current_language as LANGUAGE_CODE%} {% endcomment %}


{% block content %}


<div class="card col-lg-12 text-justify" >
    {% comment %} {%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left" > {% endcomment %}
       {% comment %} <img class="card-img-top" src="{% static 'cn.jpg' %}" height="500" alt="Card image cap"> {% endcomment %}
       <!-- Image Slider Container -->
       {% comment %} <div id="imageSlider" class="carousel slide" data-ride="carousel" data-interval="1000"> <!-- Set data-interval to the desired interval in milliseconds (e.g., 2000 for 2 seconds) -->
           <div class="carousel-inner scroll-container">
           <div class="carousel-item active">
               <img class=" w-100" src="{% static 'cn.jpg' %}" alt="Cinque Terre">
           </div>
           <div class="carousel-item">
               <img class=" w-100" src="{% static 'cn.jpg' %}" alt="Forest">
           </div>
           <div class="carousel-item">
               <img class="w-100" src="{% static 'cn.jpg' %}" alt="Northern Lights">
           </div>
           <div class="carousel-item">
               <img class=" w-100" src="{% static 'cn.jpg' %}" alt="Mountains">
           </div>
           </div>
       </div> {% endcomment %}
       <div class="container mt-100">
            <img class="d-block w-100" src="{% static 'cn.jpg' %}" height="600" width="100" alt="Second slide">
            {% comment %} <div class="carousel-caption">
                <a class="nav-link btn btn-success" href="{% url 'app1:cv' %}"<h4 class="card-title text-center ">{% trans "السيرة الذاتية" %}</h4></a>
                <a class="nav-link btn btn-success" href="{% url 'app1:bienvenu' %}"<h4 class="card-title text-center ">{% trans "كلمة ترحيب" %}</h4></a>
            </div> {% endcomment %}
       </div>
       <div class="card-body">
         <h4 class="card-title text-center ">{% trans "كلمة ترحيب" %}</h4>
         <p class="card-text">
           {% trans "في إطار مهمتها العامة المتمثلة في حماية ورعاية مصالح المواطنين الموريتانيين المقيمين بالمملكة المغربية أو العابرين لها، وحرصا على التواصل مع هؤلاء المواطنين وتقريب الخدمات منهم، تجسيدا للإرادة السامية لفخامة رئيس الجمهورية السيد محمد ولد الشيخ الغزواني بربط الصلة بالجالية الوطنية في الخارج وجعلها على في صلب الرعاية والاهتمام ، ومن أجل د تفاعل أكثر سرعة وانسيابا مع تطلعات هؤلاء المواطنين ،جاء قرار افتتاح القنصلية العامة للجمهورية الإسلامية الموريتانية بالدار البيضاء لتشكل أداة لخدمة أفراد جاليتنا بالمملكة المغرية الشقيقة ، وإنه ليسعدنا في القنصلية أن نضع رهن إشارة أفراد جاليتنا هذا الموقع الألكتروني ليشكل منصة للتفاعل وتوفير المعلومات المهمة لهم ، آملين أن يجدو فيه ما يحتاجونه من معلومات وتوجيهات تسهل حصولهم على الخدمات وتبسط الإجراءان ، دون أن يكون بديلا عن تواصلهم المباشر مع القنصلية التي ستكون بكافة مصالحها وطواقمها رهن إشارتهم وتحت تصرفهم." %}
         </p>
         <span>{% trans "القنصل العام :" %} {% trans "الطالب المختار الشيخ محمد المجتبى" %}</span>
       </div>
</div>
<div class="card-body">
    {% comment %} <a class="nav-link btn btn-success" href="{% url 'app1:bienvenu' %}"<h4 class="card-title text-center ">{% trans "كلمة ترحيب" %}</h4></a> {% endcomment %}
    <a class="nav-link btn btn-success" href="{% url 'app1:cv' %}"><h4 class="card-title text-center ">{% trans "السيرة الذاتية" %}</h4></a>

</div>
    

   {% comment %} <a class="dropdown-item" href="{% url 'app1:bienvenu' %}">{% trans "كلمة ترحيب"%} </a>
    <a class="dropdown-item" href="{% url 'app1:cv' %}">{% trans "السيرة الذاتية للقنصل العام"%}</a> {% endcomment %}





{% endblock %}

app1/templates/app1/contact.html
{% extends 'base.html'%}
{%load static %}
{% load i18n %}
{% comment %} {% load i18n %}

{%get_current_language as LANGUAGE_CODE%} {% endcomment %}


{% block content %}

<br>

<!--start contacter -->
<div class="pb-3">
    <div class="bg-light py-2 px-4 mb-3">
        <h3 class="m-0  {%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left"> {% trans "التواصل مع القنصلية" %} </h3>
    </div>
    <div class="bg-light text-center p-4 mb-3">
        <ul class="list-group">
            {% comment %} <a href="https://www.diplomatie.gov.mr/"> {% endcomment %}
                <li class="list-group-item d-flex justify-content-between align-items-center  text-justify">
                    {% trans ": العنوان " %}
                    <span> {% trans "زنقة ..................." %} </span>
                </li>
            {% comment %} </a> {% endcomment %}
            {% comment %} <a href="http://www.ami.mr/"> {% endcomment %}
                <li class="list-group-item d-flex justify-content-between align-items-center text-justify">
                    {% trans "هاتف :" %}
                    {%if LANGUAGE_CODE == 'ar' %}
                        <span> 24242525 222+ </span>
                    {% else%} 
                        <span> +222 24242525 </span>
                    {% endif %}
                    
                
                </li>
            {% comment %} </a> {% endcomment %}
            {% comment %} <a href="http://www.pmd.mr/pages/ar/"> {% endcomment %}
                <li class="list-group-item d-flex justify-content-between align-items-center text-justify">
                    {% trans "البريد الالكتروني : " %}   
                    <span>exemple2023@gmail.com</span>
                </li>
            {% comment %} </a> {% endcomment %}
        </ul>
    </div>
</div>
<!-- end contacter -->
 <!--start work -->
 <div class="pb-3">
    <div class="bg-light py-2 px-4 mb-3">
        <h3 class="m-0  {%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left"> {% trans "أوقات الدوام" %} </h3>
    </div>
    <div class="bg-light text-justify p-4 mb-3">
        <ul class="list-group">
                <li class="list-group-item d-flex justify-content-between align-items-center ">
                 <h6 class="col-5"> {% trans "الدوام العادي :" %} </h6> 
                    <p> {% trans "من التاسعة والنصف صباحا حتى الرابعة والنصف مساء باستثناء يوم الجمعة من الثامنة حتى الثانية عشر" %} </p>
                </li>
                <li class="list-group-item d-flex justify-content-between align-items-center">
                    <h6 class="col-5"> {% trans "الدوام في شهر رمضان :" %} </h6>
                    <p> {% trans "من التاسعة والنصف حتى الثالثة ." %} </p>
                
                </li>
        </ul>
    </div>
</div>

{% endblock %}

app1/templates/app1/cv.html
{% extends 'base.html'%}
{%load static %}
{% load i18n %}
{% comment %} {% load i18n %}

{%get_current_language as LANGUAGE_CODE%} {% endcomment %}


{% block content %}

<div class="card col-lg-12 text-justify" >
    {% comment %} {%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left" > {% endcomment %}
       {% comment %} <img class="card-img-top" src="{% static 'cn.jpg' %}" height="500" alt="Card image cap"> {% endcomment %}
       <!-- Image Slider Container -->
       {% comment %} <div id="imageSlider" class="carousel slide" data-ride="carousel" data-interval="1000"> <!-- Set data-interval to the desired interval in milliseconds (e.g., 2000 for 2 seconds) -->
           <div class="carousel-inner scroll-container">
           <div class="carousel-item active">
               <img class=" w-100" src="{% static 'cn.jpg' %}" alt="Cinque Terre">
           </div>
           <div class="carousel-item">
               <img class=" w-100" src="{% static 'cn.jpg' %}" alt="Forest">
           </div>
           <div class="carousel-item">
               <img class="w-100" src="{% static 'cn.jpg' %}" alt="Northern Lights">
           </div>
           <div class="carousel-item">
               <img class=" w-100" src="{% static 'cn.jpg' %}" alt="Mountains">
           </div>
           </div>
       </div> {% endcomment %}
       <div class="container mt-100">
            <img class="d-block w-100" src="{% static 'cn.jpg' %}" height="600" width="100" alt="Second slide">
            
       </div>
       <div class="card-body">
         {% comment %} <h4 class="card-title text-center ">{% trans "كلمة ترحيب" %}</h4>
         <p class="card-text">
           {% trans "في إطار مهمتها العامة المتمثلة في حماية ورعاية مصالح المواطنين الموريتانيين المقيمين بالمملكة المغربية أو العابرين لها، وحرصا على التواصل مع هؤلاء المواطنين وتقريب الخدمات منهم، تجسيدا للإرادة السامية لفخامة رئيس الجمهورية السيد محمد ولد الشيخ الغزواني بربط الصلة بالجالية الوطنية في الخارج وجعلها على في صلب الرعاية والاهتمام ، ومن أجل د تفاعل أكثر سرعة وانسيابا مع تطلعات هؤلاء المواطنين ،جاء قرار افتتاح القنصلية العامة للجمهورية الإسلامية الموريتانية بالدار البيضاء لتشكل أداة لخدمة أفراد جاليتنا بالمملكة المغرية الشقيقة ، وإنه ليسعدنا في القنصلية أن نضع رهن إشارة أفراد جاليتنا هذا الموقع الألكتروني ليشكل منصة للتفاعل وتوفير المعلومات المهمة لهم ، آملين أن يجدو فيه ما يحتاجونه من معلومات وتوجيهات تسهل حصولهم على الخدمات وتبسط الإجراءان ، دون أن يكون بديلا عن تواصلهم المباشر مع القنصلية التي ستكون بكافة مصالحها وطواقمها رهن إشارتهم وتحت تصرفهم." %}
         </p>
         <span>{% trans "القنصل العام :" %} {% trans "الطالب المختار الشيخ محمد المجتبى" %}</span> {% endcomment %}
         <div class="card col-lg-12 {%if LANGUAGE_CODE == 'ar' %} text-right {% endif%} text-left" {%if LANGUAGE_CODE == 'ar' %} direction= "rtl" {% endif%} direction= "ltr">
            <div class="row">
                <div class="col-lg-12 ">
        
                    <h2 class="mt-4 text-center ">{% trans "السيرة الذاتية" %}</h2>
                    <hr>

                    <h1 class='text-justify'>
                         {% trans "جاري تحديث الصفحة"%}
                    </h1>
        
                    {% comment %} <h3>{% trans "المؤهلات التعليمية" %}</h3>
                    <ul>
                        <li>{% trans "ماجستير في العلوم السياسية - جامعة محمد الخامس، الرباط، المغرب (2015-2017)" %}</li>
                        <li>{% trans "بكالوريوس في العلاقات الدولية - جامعة نواكشوط، موريتانيا (2011-2015)" %}</li>
                    </ul>
        
                    <h3 class="mt-4">{% trans "الخبرات المهنية" %}</h3>
                    <ul>
                        <li>{% trans "القنصل العام لموريتانيا بالدار البيضاء، المغرب (2022-الآن)" %}</li>
                        <li>{% trans "المستشار السياسي في السفارة الموريتانية بباريس، فرنسا (2017-2022)" %}</li>
                        <li>{% trans "باحث في مركز الدراسات السياسية والاستراتيجية في نواكشوط، موريتانيا (2015-2017)" %}</li>
                    </ul>
        
                    <h3 class="mt-4">{% trans "المهارات" %}</h3>
                    <h4>{% trans "المهارات اللغوية" %}</h4>
                    <ul>
                        <li>{% trans "العربية (اللغة الأم)" %}</li>
                        <li>{% trans "الفرنسية (بطلاقة)" %}</li>
                        <li>{% trans "الإنجليزية (جيد)" %}</li>
                    </ul>
        
                    <h4 class="mt-4">{% trans "المهارات التقنية" %}</h4>
                    <ul>
                        <li>{% trans "إجادة استخدام برامج Microsoft Office" %}</li>
                        <li>{% trans "إجادة استخدام الإنترنت" %}</li>
                        <li>{% trans "إجادة استخدام برامج الترجمة الآلية" %}</li>
                    </ul>
        
                    <h4 class="mt-4">{% trans "المهارات الشخصية" %}</h4>
                    <ul>
                        <li>{% trans "القدرة على العمل تحت الضغط" %}</li>
                        <li>{% trans "القدرة على العمل الجماعي" %}</li>
                        <li>{% trans "القدرة على التواصل الفعال" %}</li>
                    </ul>
        
                    <h3 class="mt-4">{% trans "الأهداف المهنية" %}</h3>
                    <p>{% trans "العمل في مجال الدبلوماسية والعلاقات الدولية، المساهمة في تعزيز العلاقات بين موريتانيا ودول العالم، إحداث تأثير إيجابي على المجتمع." %}</p>
                 {% endcomment %}
                </div>
            </div>
        </div>
    </div>
</div>

<div class="card-body">
    <a class="nav-link btn btn-success" href="{% url 'app1:bienvenu' %}"><h4 class="card-title text-center ">{% trans "كلمة ترحيب" %}</h4></a>
    {% comment %} <a class="nav-link btn btn-success" href="{% url 'app1:cv' %}"<h4 class="card-title text-center ">{% trans "السيرة الذاتية" %}</h4></a> {% endcomment %}

</div>





{% endblock %}

app1/templates/app1/details_page.html
{% extends 'base.html'%}
{%load static %}
{% comment %} {% load i18n %}

{%get_current_language as LANGUAGE_CODE%} {% endcomment %}


{% block content %}


<div class="card col-lg-12 text-justify" >
{% comment %} text-right" > {% endcomment %}
    {% if poste.video_url == "" %}
        <img class="card-img-top" src="{{ poste.image_url }}" height="500" alt="Card image cap">
    {% else %}
        <div class="card-img-top">
            <div class="embed-responsive embed-responsive-16by9">
                <!-- Replace the YouTube video URL in the src attribute -->
                <iframe class="embed-responsive-item" src="{{ poste.video_url }}" allowfullscreen></iframe>
            </div>
        </div>
    {% endif %}
    <div class="card-body">
      <h4 class="card-title text-center ">{{poste.title}}</h4>
      <p class="card-text">{{ poste.content | safe }}</p>
      <div class='col'>
        <span>{{poste.author}}</span>
        <span>{{poste.published_date}}</span>
      </div>
    </div>
</div>





{% endblock %}

app1/templates/app1/fonctions_du_consulat.html
{% extends 'base.html' %}
{% load i18n %}

{% get_current_language as LANGUAGE_CODE %}

{% block content %}

<div class="col">
    
    <div class="col text-justify">
        <h2 class="text-center">{% trans "مهام القنصلية:" %}</h2>
        <p>
            {% trans "" %}
        </p>
    </div>

</div>
{% endblock %}